language: node_js
node_js:
  - "6"

before_install:
  - npm i -g jspm
  - jspm registry export github

install:
  - wget  'https://dist.ipfs.io/go-ipfs/v0.4.2/go-ipfs_v0.4.2_linux-amd64.tar.gz'
  - tar xvfz go-ipfs_v0.4.2_linux-amd64.tar.gz
  - export PATH=$PWD/go-ipfs/ipfs:$PATH
  - npm install --prefix ./desktop-app ./desktop-app
  - npm run build --prefix ./desktop-app ./desktop-app

script:
  - npm run test:lint --prefix ./desktop-app
  - npm run coverall --prefix ./desktop-app

after_success:
  - coveralls
