const client = require('./api/client.js')
const file = require('./api/file.js')

client.run(0)
client.run(0)
client.run(0)
client.run(1)
client.run(0)
client.run(0)
client.run(2)
client.run(2)
  .then(() => file.add(0, 'data100k', 'data'))
  .then(() => {
    console.log('success!')
    client.kill()
    process.exit()
  })
  .catch((err) => console.log(err))
