# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'StoreIt' do
    pod 'ObjectMapper'
    pod 'CryptoSwift'
    pod 'Starscream'
    pod 'p2.OAuth2'
    pod 'Plist'
    pod 'FBSDKLoginKit'
    pod 'FBSDKCoreKit'
    pod 'Alamofire'
end

target 'StoreItTests' do

end

target 'StoreItUITests' do

end