# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'StoreIt' do
    pod 'ObjectMapper'
    pod 'CryptoSwift'
    pod 'Starscream'
    pod 'Plist'
    pod 'FBSDKLoginKit'
    pod 'FBSDKCoreKit'
    pod 'Google/SignIn'
    pod 'Alamofire'
    pod 'SwiftKeychainWrapper', :git => 'https://github.com/jrendel/SwiftKeychainWrapper.git', :branch => 'develop'
end

target 'StoreItTests' do

end

target 'StoreItUITests' do

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end